### ISSUE TITLE
Get clustering working

### ISSUE THREAD

**Issue by GarrettGenz** [GarrettGenz/FestivalMapAPI#3]

**Comment by slickpickle** [comment]
https://xhr.spec.whatwg.org/#introduction

Sounds like httpXMLrequest needs to be swapped out since it's
transitioning, but don't think this is what's causing my error. It's just
the first part of the error i sent. I imagine it would pop up for you in
the developer tool when you hit the search button.

**Comment by slickpickle** [comment]
fucking nvm. was a cached file that i just needed to clear.
